version: '3'

services:
  web:
    image: node:latest
    depends_on:
    - "api"
    environment:
    - VUE_APP_APIURL=http://localhost:3000
    command:
      - /bin/sh
      - -c
      - |
        cd code
        npm i
        npm rebuild node-sass
        npm run serve
    volumes:
      - .:/code
    ports:
      - "8080:8080"
  api:
    image: 
      bernardoms/scalemusicapi:latest
    environment:
      - PORT=3000
    ports: 
    - "3000:3000"
