version: '3'

services:
  web:
    image: node
    command:
      - /bin/sh
      - -c
      - |
        cd code
        npm i
        npm run serve
    volumes:
      - .:/code
    ports:
      - "8080:8080"